### ISSUE TITLE
Question Urgent, how to add metadata?

### ISSUE THREAD

**Issue by Elmahfoud-Oul** [ton-community/compressed-nft-contract#6]
I had problem, when i mint by send TON to contract address generated, I deploy contract of cNFT collection right but the problem I don't know where can I add the metadata as code64 or as URL or any type any one can help or a guide.
Urgent pls

**Comment by Michellecasiddy** [comment]
> I had problem, when i mint by send TON to contract address generated, I deploy contract of cNFT collection right but the problem I don't know where can I add the metadata as code64 or as URL or any type any one can help or a guide.
> Urgent pls

@Elmahfoud-Oul You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID TON07638
Please see the link below to our dedicated support line:
[Ton Network DApps Support Ticket Requests](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Michellecasiddy** [comment]
> I had problem, when i mint by send TON to contract address generated, I deploy contract of cNFT collection right but the problem I don't know where can I add the metadata as code64 or as URL or any type any one can help or a guide. Urgent pls

@Elmahfoud-Oul Has your issue already been escalated?

**Comment by Darrenpeaker** [comment]
> I had problem, when i mint by send TON to contract address generated, I deploy contract of cNFT collection right but the problem I don't know where can I add the metadata as code64 or as URL or any type any one can help or a guide. Urgent pls

@Elmahfoud-Oul Has your issue already been escalated?

**Comment by Elmahfoud-Oul** [comment]
> > I had problem, when i mint by send TON to contract address generated, I deploy contract of cNFT collection right but the problem I don't know where can I add the metadata as code64 or as URL or any type any one can help or a guide. Urgent pls
> 
> @Elmahfoud-Oul Has your issue already been escalated?

Not yet, any solution from you men

**Comment by Elmahfoud-Oul** [comment]
> > I had problem, when i mint by send TON to contract address generated, I deploy contract of cNFT collection right but the problem I don't know where can I add the metadata as code64 or as URL or any type any one can help or a guide. Urgent pls
> 
> @Elmahfoud-Oul Has your issue already been escalated?

Not yet, any solution from you men

**Comment by Darrenpeaker** [comment]
> > > I had problem, when i mint by send TON to contract address generated, I deploy contract of cNFT collection right but the problem I don't know where can I add the metadata as code64 or as URL or any type any one can help or a guide. Urgent pls
> > 
> > 
> > @Elmahfoud-Oul Has your issue already been escalated?
> 
> Not yet, any solution from you men

@Elmahfoud-Oul To add metadata to your cNFT collection, you can include it as a base64 encoded string directly in your smart contract code. Have you tried that out ?

**Comment by Elmahfoud-Oul** [comment]
> > > > I had problem, when i mint by send TON to contract address generated, I deploy contract of cNFT collection right but the problem I don't know where can I add the metadata as code64 or as URL or any type any one can help or a guide. Urgent pls
> > > 
> > > 
> > > @Elmahfoud-Oul Has your issue already been escalated?
> > 
> > 
> > Not yet, any solution from you men
> 
> @Elmahfoud-Oul To add metadata to your cNFT collection, you can include it as a base64 encoded string directly in your smart contract code. Have you tried that out ?

The problem I know you should turn the metadata to base64 code, But I don't know the syntax of of deploy and add with it base64 of metadata 
BTW, are you have any guide that explain that or if you can give me lists

**Comment by Elmahfoud-Oul** [comment]
> > > > I had problem, when i mint by send TON to contract address generated, I deploy contract of cNFT collection right but the problem I don't know where can I add the metadata as code64 or as URL or any type any one can help or a guide. Urgent pls
> > > 
> > > 
> > > @Elmahfoud-Oul Has your issue already been escalated?
> > 
> > 
> > Not yet, any solution from you men
> 
> @Elmahfoud-Oul To add metadata to your cNFT collection, you can include it as a base64 encoded string directly in your smart contract code. Have you tried that out ?




> > > > I had problem, when i mint by send TON to contract address generated, I deploy contract of cNFT collection right but the problem I don't know where can I add the metadata as code64 or as URL or any type any one can help or a guide. Urgent pls
> > > 
> > > 
> > > @Elmahfoud-Oul Has your issue already been escalated?
> > 
> > 
> > Not yet, any solution from you men
> 
> @Elmahfoud-Oul To add metadata to your cNFT collection, you can include it as a base64 encoded string directly in your smart contract code. Have you tried that out ?

can you give me command structure I can run, for example
[path-to-update-file] [collection-owner] [collection-meta] [item-meta-prefix] [royalty-base] [royalty-factor] [royalty-recipient] [api-uri-including-v1]
cause the problem there no guide of command in guide

**Comment by benamivip12** [comment]
my telegram @VANGUARD133
